arch:
  - amd64
os: linux
env:
  global:
    - secure: "cp3Ttn9Q5Ia17cMpPbNMlc1OVRzgN96b730agmbwtH8W9HnbY+cqw/dKVv4pJJNX1lK4ABdiCFo4S4prB5DhNtg/h40DCeNu/AG8Ha54Xx1Mat2Qe29Qxik8gp3OdV5acpoY5TKLFYhyNvXdv6jyXblE6c/q62zQKzE6+TlcjMOsxq/gLQSkVSbBFcWGg95zlebLWfPVyHo0FjD+Athn2gAz0/0BN8n8rC+lnNjs+NFyDvqC/322gDriSQdFlYuchFQeYLxAVFGTdkwD6en75VpPxRNNJ0+0DhWsS5F2Ch1PjtTQ0rU9nNxZn0U0jqerRHXM36gOZhRjv7mmi3dy0IXDVMZiPFRVrJc86vC5Q9oul20VRX0m/YI5bd4Y/aXr2hJNXp2CMfmotr4SijCIxnJVpa2RGPF2K7UlNYQ4CrQ/m83KXZ2/9ez/DqsuibY1bJ0oxWqo4w4+q8GziUnqn9UsOrmHUn/OMqeqSL/x1WORCRRBu96Xdz5V7oA9BCAMsbEyuJZQDi55LgqPYRV4ctkdcGJFEsoUeRswnq8Tvk/ZLSuppAH251HBw8nJSquzAv5vrkNDvHqwaAnu7aVr0NR39iIYFWO8CRgmK3QKBYwKs3QDAYRk+cQg/h/WG9eKesjAfOdJN3cMqmuMb51+L8tCepdms9Qf0mP9/9sKsqw="
    - secure: "GljKtcsWdC5/HI6rMCr5GyzhffkrYQFkqE/4mzLftrgx/Do308qCYZM0anvI4yWoIo17JiqVtwIdxEzAJZK/kTwzSwgjELQzzo23QrJYGNlxuoIaqb6eomT88J8HoxOXWGyYwLBb89WrqMpAY0jS5lQ2YjOdnwiuRk0NLCY45nRvVQV4Hez1VkO/oc6UtHn36cZLRbXNBplXcbWoFXE0NUKuy2HVO4NBSTHwTrOrMfJ4tQ2IO+gvqT9rcZy3mepuv59ouDEGFG/lesWZpOXZOjCc879pfKcHHW3HPjFPUTqhb/jCObw5qp6ysUOqeQHtkzIYu3J42zwfE0ZGOc3tZwlueXW9fG2Q3BFp4EDTUbZgEq4dsSNxmsdcyF9LYrOezP+c37yMw01raiLsdoAYFgMFV2JIRHJbVXelxUdaCPPpr5tyPEMSo+OePJpoRCRI6Q5M0kpnJ7NP9L/g5Uyr+CSP420cPxlu9yGfWsQ8z48k0aCrZpR0Masw6H0rz5ITWyE6W2u/Pb4poopA+ARgNSYST/jGhxiw9EgeJNlD1fRSjlzKIykpYs6NDtIxhm7XPOamgponOlzOxdgSx4L9vJQQU6yakNmvyKFP5A3D6gznpl1qKovzXah6bNn49w5q66ygeaighZVsAbpzaq6X5xBRjcJ/Zjou14eM5oYF5XM="
services:
  - docker
script:
  - docker pull ohtukonenako/ohtuprojekti_kesa2020:latest
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yesdocker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker build -f Dockerfile.arm -t ohtukonenako/ohtuprojekti_kesa2020:latest --cache-from ohtukonenako/ohtuprojekti_kesa2020:latest .
  - docker network create rosnet
  - docker run -it --rm \
    --net rosnet \
    --privileged \
    --name testing \
    --env ROS_HOSTNAME=testing \
    --env ROS_MASTER_URI=http://master:11311 \
    ohtukonenako/ohtuprojekti_kesa2020:latest bash -c "cd src/ohtu && poetry run /bin/bash -c 'source ../../devel/setup.bash && cd ../../ && ROS_HOME=/catkin_ws/src/ohtu/src catkin_make run_tests && catkin_test_results'"
deploy:
  - provider: script
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push ohtukonenako/ohtuprojekti_kesa2020:latest
    on:
      branch: master
