version: "3.4"
services:
  master:
    container_name: "master"
    networks:
      - rosnet
    image: ros:melodic-ros-core
    command: >
        /bin/bash -c "cd /
        && roscore
        && /opt/ros/melodic/bin/rosparam set label_file mscoco_complete_labels
        && /opt/ros/melodic/bin/rosparam set model_file ssd_mobilenet_v1_1_metadata_1.tflite"

  rosdetector:
    container_name: "rosdetector"
    networks:
      - rosnet
    depends_on:
      - master
    build: 
      context: .
      target: rosobjectdetector
    environment:
      - "ROS_HOSTNAME=rosdetector"
      - "ROS_MASTER_URI=http://master:11311"
    tty: True

  rosinput:
    container_name: "rosinput"
    networks:
      - rosnet
    depends_on:
      - master
    build:
      context: .
      target: rosinput
    environment:
      - "ROS_HOSTNAME=rosinput"
      - "ROS_MASTER_URI=http://master:11311"
    stdin_open: true
    tty: true

  rosprinter:
    container_name: "rosprinter"
    networks:
      - rosnet
    depends_on:
      - master
    build:
      context: .
      target: rosprinter
    environment:
      - "ROS_HOSTNAME=rosprinter"
      - "ROS_MASTER_URI=http://master:11311"
    logging:
      driver: none
    tty: true
    stdin_open: true

  roscamera:
    container_name: "roscamera"
    networks:
      - rosnet
    depends_on:
      - master
    build:
      context: .
      target: roscamera
    environment:
      - "ROS_HOSTNAME=roscamera"
      - "ROS_MASTER_URI=http://master:11311"
    logging:
      driver: none
    devices:
      - /dev/video0:/dev/video0
    tty: true
    stdin_open: true
    privileged: True

  rosqrnode:
    container_name: "rosqrnode"
    networks:
      - rosnet
    depends_on:
      - master
    build:
      context: .
      target: rosqrdetector
    environment:
      - "ROS_HOSTNAME=rosqrnode"
      - "ROS_MASTER_URI=http://master:11311"
    logging:
      driver: none
    tty: true
    stdin_open: true

networks:
  rosnet:
