version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: circleci/python:3.7.7
    steps:
    - checkout
    - add_ssh_keys:
      fingerprints:
        - "3a:fd:8a:69:40:1b:3c:76:30:3e:da:a5:a7:c6:8d:c6"
    - run: sudo apt install tree
    - run: tree
    - run: git status
    - run: touch testfile
    - run: git status
    - run: git config --global user.email "app@circleci.com"
    - run: git config --global user.name "CircleCI"
    - run: git add .
    - run: git commit -m "CircleCI commit to '${CIRCLE_BRANCH}' [ci skip]"
    - run: echo ${CIRCLE_BRANCH}
    - run: git push --set-upstream origin ${CIRCLE_BRANCH}
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
    - restore_cache:
        keys:
          - konenako-{{ .Branch }}-{{ checksum "pyproject.toml" }}
          - konenako-{{ .Branch }}-
          - konenako-
    - run:
        command: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          poetry install
    - save_cache:
        paths:
          - ~/.cache/pypoetry/virtualenvs
        key: konenako-{{ .Branch }}-{{ checksum "pyproject.toml" }}
    - run: |      
          YAPF_FAIL=$(poetry run yapf -rd .);
    - run:
        command: |
          sudo apt-get update
          sudo apt-get install -y libzbar0
    - run: 
        command: |
          cd rostest
          poetry run coverage run -m unittest discover
          poetry run coverage xml
    - codecov/upload:
        file: "rostest/coverage.xml"
 
