version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: circleci/python:3.7.7
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
    - run:
        command: |
          sudo pip install pipenv
          pipenv install
          pipenv shell
    - run: 
        command: |
          cd tests
          coverage run -m unittest discover
    - run: 
        command: |
          cd tests
          coverage xml
    - codecov/upload:
          file: "./tests/coverage.xml"