version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: circleci/python:3.6.4
    steps:
    - checkout
    - run: echo $CODECOV_TOKEN
    - run: python3 -m venv env
    - run: . env/bin/activate
    - run: pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: 
        command: |
          cd tests
          coverage run -m unittest discover
          coverage xml
    - codecov/upload:
        file: "./tests/coverage.xml"
