version: 2.1

jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: circleci/python:3.6.4
    steps:
    - checkout
    - run: echo "testi"
    - run: sudo apt install tree
    - run: tree