version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: circleci/python:3.7.7
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
    - run:
        command: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          poetry install
    - run:
        command: |      
          poetry run yapf -rd .
    - run: 
        command: |
          cd rostest
          poetry run coverage run -m unittest discover
          poetry run coverage xml
    - codecov/upload:
          file: "./coverage.xml"
