version: 2.1

jobs:
  build:
    working_directory: ~/repository
    docker:
      - image: circleci/python:3.6.4
    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
    - run: sudo apt install tree
    - run: tree
    - run: CODECOV_TOKEN
    - run: python3 -m venv env
    - run: . env/bin/activate
    - run: pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: 
        command: |
          cd tests
          python3 -m unittest

